[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ocralign"
version = "0.2.0"
description = "OCR while preserving document formatting and layout, with word-level coordinate mapping for overlays"
authors = [{ name = "Hasham Ul Haq", email = "haashaamulhaq@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "PyMuPDF",
    "pytesseract",
    "Pillow",
    "tqdm"
]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["ocralign*"]
